### ISSUE TITLE
Mobile Nav Alignment Issue

### ISSUE THREAD

**Issue by alikhamesy** [sfusurge/stormhacks_website#46]
**Describe the bug**
The top nav seems to be slightly miss-aligned on Mobile  
![image](https://github.com/sfusurge/stormhacks_website/assets/40162664/13b9860c-3c18-4217-9de2-25c575a56749)

I believe you just need to set `left: 0` (+ maybe a paddingLeft if that's desired) https://github.com/sfusurge/stormhacks_website/blob/main/src/components/NavBar.jsx#L19

Thanks! :)

**Comment by ChrisFong604** [comment]
Thanks for reporting this issue! It should now be fixed through this PR: https://github.com/sfusurge/stormhacks_website/pull/49/files
